services:
  app:
    build: .
    container_name: user-admin-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      APP_JWT_SECRET: your-super-long-random-secret-key-at-least-32-bytes
      DB_URL: jdbc:postgresql://postgres:5432/user_admin_system
      DB_USER: user_admin_app
      DB_PASSWORD: password123
      DLL_AUTO: update
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: user-admin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_admin_system
      POSTGRES_USER: user_admin_app
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: