package io.github.kkusylabs.useradmin.client.core.api;

/**
 * Thrown when the API rejects a request due to invalid input or malformed data.
 *
 * <p>Typically corresponds to an HTTP {@code 400 Bad Request} response.
 */
@SuppressWarnings("serial")
public class BadRequestException extends RestClientException {

	/**
	 * Creates a new exception instance.
	 *
	 * @param message error message returned by the API or generated by the client
	 */
	public BadRequestException(String message) {
		super(message);
	}

	public BadRequestException(String message, Throwable cause) {
		super(message, cause);
	}
}