package io.github.kkusylabs.useradmin.client.core.api;

/**
 * Thrown when the requested resource does not exist or cannot be located.
 *
 * <p>
 * Typically corresponds to an HTTP {@code 404 Not Found} response.
 */
@SuppressWarnings("serial")
public class NotFoundException extends RestClientException {

	/**
	 * Creates a new exception instance.
	 *
	 * @param message error message returned by the API or generated by the client
	 */
	public NotFoundException(String message) {
		super(message);
	}
}
